import { useState } from "react";
const STORAGE_KEY_BOOKMARKS = "kjv_bookmarks";
const STORAGE_KEY_PROGRESS = "kjv_progress";
const STORAGE_KEY_NOTES = "kjv_notes";
function load(key, fallback) { try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch { return fallback; } }
function save(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} }
export function useBookmarks() { const [bookmarks, setBookmarks] = useState(() => load(STORAGE_KEY_BOOKMARKS, [])); const addBookmark = (sectionId, label, eraTitle) => { setBookmarks((prev) => { if (prev.find((b) => b.sectionId === sectionId)) return prev; const next = [{ sectionId, label, eraTitle, date: new Date().toISOString() }, ...prev]; save(STORAGE_KEY_BOOKMARKS, next); return next; }); }; const removeBookmark = (sectionId) => { setBookmarks((prev) => { const next = prev.filter((b) => b.sectionId !== sectionId); save(STORAGE_KEY_BOOKMARKS, next); return next; }); }; const isBookmarked = (sectionId) => bookmarks.some((b) => b.sectionId === sectionId); return { bookmarks, addBookmark, removeBookmark, isBookmarked }; }
export function useReadingProgress() { const [completed, setCompleted] = useState(() => load(STORAGE_KEY_PROGRESS, [])); const markComplete = (sectionId) => { setCompleted((prev) => { if (prev.includes(sectionId)) return prev; const next = [...prev, sectionId]; save(STORAGE_KEY_PROGRESS, next); return next; }); }; const markIncomplete = (sectionId) => { setCompleted((prev) => { const next = prev.filter((id) => id !== sectionId); save(STORAGE_KEY_PROGRESS, next); return next; }); }; const isCompleted = (sectionId) => completed.includes(sectionId); return { completed, markComplete, markIncomplete, isCompleted }; }
export function useNotes() { const [notes, setNotes] = useState(() => load(STORAGE_KEY_NOTES, {})); const saveNote = (sectionId, text) => { setNotes((prev) => { const next = { ...prev, [sectionId]: text }; save(STORAGE_KEY_NOTES, next); return next; }); }; const getNote = (sectionId) => notes[sectionId] || ""; return { notes, saveNote, getNote }; }
